# Generated by Django 4.0.1 on 2022-01-25 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_item_image_item_listed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 25, 23, 32, 14, 734878)),
        ),
    ]
