# Generated by Django 4.0.1 on 2022-01-26 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_item_slug_alter_item_image_alter_item_listed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 26, 19, 31, 54, 892626)),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
        ),
    ]
