# Generated by Django 4.0.1 on 2022-01-27 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_item_image_alter_item_listed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 14, 48, 10, 867955)),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 14, 48, 10, 867955)),
        ),
    ]
