# Generated by Django 4.0.1 on 2022-01-27 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_remove_order_user_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 18, 15, 3, 290005)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 18, 15, 3, 291005)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 18, 15, 3, 291005)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 18, 15, 3, 292007)),
        ),
    ]
