# Generated by Django 4.0.1 on 2022-01-28 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_item_listed_date_alter_order_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listed_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 14, 6, 38, 320362)),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 14, 6, 38, 321361)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 14, 6, 38, 321361)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 14, 6, 38, 321361)),
        ),
    ]
